name: Build Other Repository Docker Image (No Push)

on: 
  workflow_dispatch:
    inputs:
      project_path:
        description: '仓库路径'
        required: true
        default: 'wtlwang2019/llama.cpp'
      image_name:
        description: '镜像名称'
        required: true
        default: 'llama-full'        

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout other repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.project_path }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check ENV
        run: |
          pwd
          ls
          ls -l 
          df -h
          
      - name: Pull Docker Images and Package
        env: 
          image: ${{ inputs.image_name }}
          image_name: ${{ inputs.image_name }}
        run: |
            pwd
            ls
            docker build -t ${image}:local .
            docker images -a
            docker save "${image}:local" -o "${image_name}-amd64.tar"
            gzip -c "${image_name}-amd64.tar" > "${image_name}-amd64.tar.gz"
            rm "${image_name}-amd64.tar"
            ls
            # mv *.tar.gz ../

  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-artifact
          path: ${{ github.workspace }}/*.tar.gz
          retention-days: 5  # 将保留天数设置为 1 天 最多可设置90天
