name: RUN ARM64 Docker Image

on: 
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'docker image的tag'
        required: true
        default: 'ghcr.io/wtlwang2019/llama_cpp:arm64'
      entrypoint:
        description: 'docker image运行的entrypoint,例如/bin/bash'
        required: false
        default: ''
      cmd:
        description: '运行镜像的命令, 例如ls -l; null表示使用默认cmd'
        required: true
        default: '-h'      
      

jobs:
  run:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
          
      - name: Run arm64 docker image
        env: 
          image: ${{ inputs.image_tag }}
          # cmd: ${{ inputs.cmd }}
          entrypoint: ${{ inputs.entrypoint }}
        run: |
            pwd
            ls
            cmd="${{ inputs.cmd }}"
            docker pull $image
            docker images -a
            docker inspect $image
            opt="--entrypoint $entrypoint"
            # 使用镜像自带的entrypoint，不挂在/test目录
            if [ -z "$entrypoint" ]; then 
              if [ "$cmd" = "null" ]; then
                docker run --rm ${image}
              else
                docker run --rm  ${image}  ${cmd}
              fi
            elif [ "$cmd" = "-h" ]; then
              docker run --rm $opt -v ./test:/test ${image} /test/run.sh
            else
              docker run --rm $opt -v ./test:/test ${image} -c "$cmd"
            fi
            
            # echo "docker run --rm -i $opt ${image}  $cmd"
            # docker run --rm -i $opt  ${image}  ${cmd}
            ls -l test
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}/test/*.{log,txt}
          retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天
