name: RUN ARM64 Docker Image

on: 
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'docker image的tag'
        required: true
        default: 'ghcr.io/wtlwang2019/llamacpp:arm64'
      cmd:
        description: '运行镜像的命令, 例如/bin/bash'
        required: true
        default: '-h'      
      

jobs:
  run:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
          
      - name: Run arm64 docker image
        env: 
          image: ${{ inputs.image_tag }}
          cmd: ${{ inputs.cmd }}
        run: |
            pwd
            ls
            docker pull $image
            docker images -a
            docker run --rm -i  ${image}  $cmd

  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}/*.tar.gz
          retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天
