name: Cleanup GHCR packages

on:
  # schedule:
  #   - cron: '0 0 * * 0'  # Run weekly on Sundays
  workflow_dispatch:     # Allow manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write    # Required for package deletion
      
    steps:
      # - name: Cleanup old packages
      #   uses: 404cerebrum/cleanup-ghcr-packages@v1
      #   with:
      #     # Required inputs:
      #     token: ${{ secrets.GITHUB_TOKEN }}
          
      #     # Optional inputs (shown with defaults):
      #     # org: ''                          # Organization name (if using org account)
      #     username: ${{ github.repository_owner }}  # Username (if using personal account)
      #     package-name: 'llamacpp'                 # Defaults to repository name if empty
      #     days: '3'                       # Number of days to keep packages 
      #     dry-run: 'false'                 # Set to 'true' to only list packages without deleting
      - name: Cleanup old packages 2
        uses: smartsquaregmbh/delete-old-packages@v0.8.1
        with:
          user: ${{ github.repository_owner }}
          type: container
          keep: 0
          names: |
            llamacpp
          
